name: docker-publish

on:
  push: {}

permissions:
  contents: write
  packages: write

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: luzifer/actions/docker-publish@ec4b20851e8c71c469406bbf5f25d8af685cc779 # develop
        with:
          image: ghcr.io/luzifer-docker/code-server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
