name: docker-publish

on:
  push: {}

permissions:
  contents: write
  packages: write

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: luzifer/actions/docker-publish@032da29d4fb988e8209bed077a1c3d834468431a # develop
        with:
          image: ghcr.io/luzifer-docker/code-server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
