name: docker-publish

on:
  push: {}

permissions:
  contents: write
  packages: write

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: luzifer/actions/docker-publish@fe674b660989d3a32e54f50355fbf9e3b31f5d0e # develop
        with:
          image: ghcr.io/luzifer-docker/code-server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
